### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by newtester805** [BrandonHanx/mmf#10]
## ❓ Questions and Help
Hello,

First of all, thank you very much for the clear paper and code!

I am trying to fine-tune pre-trained FashionViL on TGIR on FashionIQ using the command in the README.md with a PC with 4 Tesla M60. From the paper, you needed 5.5hs to complete the fine tuning with 1 RTX 3090.

According to [this](https://technical.city/en/video/Tesla-M60-vs-GeForce-RTX-3090) comparison RTX 3090 is about 3.5 times quicker than my Tesla. So, using DDP I was expecting around the same: 5 or 6 hours to complete.

The logs, however, show a ETA of 15h.

Any idea about this difference in performance?

Many thanks in advance.

**Comment by BrandonHanx** [comment]
Hi thanks for your interest,

Sorry, I don't know the exact reason for this difference. But I am sure there are many factors that will influence this, such as pytorch version, CUDA version, CPU, DDP (since only 1 3090 is used by me but you are using 4 M60 so the communication among gpus is needed).

I also shared my fine-tuned ckpt in this issue (https://github.com/BrandonHanx/mmf/issues/7#issuecomment-1320882600). You can use it directly.

**Comment by newtester805** [comment]
Indeed.  There is so much need of low-cost resources for researches/ML practitioners...
Thank you very much for the tuned model.
Best wishes.

**Comment by BrandonHanx** [comment]
good luck :)
