### ISSUE TITLE
Run OCIR prediction

### ISSUE THREAD

**Issue by pntt3011** [BrandonHanx/mmf#4]
## ❓ Questions and Help
Hi, suppose I have `PolyvoreOutfits` dataset and a list of image ids (like `questions` attr in `ocir_disjoint_test.json`), how can I predict the `blank` id for OCIR task?

I read your evaluation code but it just calculates the similarity between the prediction and ground-truth embedding (please correct me if I'm wrong). 

I also run the `prediction.py` instead of `run.py` but the report file is just `[]`.
Any advice would be much appreciated.

**Comment by BrandonHanx** [comment]
Yes, you are right, OCIR is a retrieval task rather than a prediction task.
We are following the setting of `Fashion outfit complementary item retrieval, CVPR2020`.

`prediction.py` is used to predict data without ground truth, you need to define post-processing to get the expected output. We didn't use it in our pipeline.

**Comment by pntt3011** [comment]
Thank you for your reply. I will close this now.
